name: Build, Commit, Tag and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-commit-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set to your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./plugin-settings

      - name: Build
        run: npm run build
        working-directory: ./plugin-settings

      - name: Commit built assets
        run: |
          git config --local user.email "support@codedesign.app"
          git config --local user.name "GitHub Action"
          git add -A  # Add all changes, including package-lock.json
          git diff --staged --quiet || git commit -m "Build assets"
          git push

      - name: Create a new tag based on commit count
        id: tag_version
        run: |
          echo "Creating a new tag"
          TAG_VERSION=v$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
          echo "New tag version $TAG_VERSION"
          echo ::set-output name=TAG_VERSION::$TAG_VERSION

      - name: Push the new tag
        run: |
          git tag ${{ steps.tag_version.outputs.TAG_VERSION }}
          git push origin ${{ steps.tag_version.outputs.TAG_VERSION }}

      - name: Archive the entire plugin directory
        run: |
          zip -r codedesign-wp-plugin-latest.zip . -x "*.git*"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: Release ${{ env.TAG_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./codedesign-wp-plugin-latest.zip
          asset_name: codedesign-wp-plugin-latest.zip
          asset_content_type: application/zip
